### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1030: ordinal not in range(128) during install on python 3.4

### ISSUE THREAD

**Issue by mriedem** [sigmavirus24/rfc3986#13] opened 2015-05-29 20:54 UTC
Copied from openstack nova launchpad bug:

https://bugs.launchpad.net/nova/+bug/1460206

http://logs.openstack.org/15/186315/4/check/gate-nova-python34/c48b0f5/console.html#_2015-05-29_15_57_16_241

```
2015-05-29 15:57:16.241 | Collecting rfc3986>=0.2.0 (from -r /home/jenkins/workspace/gate-nova-python34/requirements.txt (line 46))
2015-05-29 15:57:16.241 | Downloading http://pypi.region-b.geo-1.openstack.org/packages/source/r/rfc3986/rfc3986-0.2.2.tar.gz
2015-05-29 15:57:16.241 | Complete output from command python setup.py egg_info:
2015-05-29 15:57:16.241 | Traceback (most recent call last):
2015-05-29 15:57:16.242 | File "<string>", line 20, in <module>
2015-05-29 15:57:16.242 | File "/tmp/tmp.ALfXvU5OeC/pip-build-ottfpn10/rfc3986/setup.py", line 22, in <module>
2015-05-29 15:57:16.242 | readme = f.read()
2015-05-29 15:57:16.242 | File "/home/jenkins/workspace/gate-nova-python34/.tox/py34/lib/python3.4/encodings/ascii.py", line 26, in decode
2015-05-29 15:57:16.242 | return codecs.ascii_decode(input, self.errors)[0]
2015-05-29 15:57:16.242 | UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1030: ordinal not in range(128)
2015-05-29 15:57:16.242 |
2015-05-29 15:57:16.242 | ----------------------------------------
2015-05-29 15:57:16.242 | Command "python setup.py egg_info" failed with error code 1 in /tmp/tmp.ALfXvU5OeC/pip-build-ottfpn10/rfc3986
```

Looks like it might be an encoding problem with the README.rst?

**Comment by mriedem** [comment] 2015-05-29 21:44
Looks like this is probably the fix:

https://review.openstack.org/#/c/186922/

openstack tests with tox >= 2 which doesn't pass local environment variables anymore.

**Comment by sigmavirus24** [comment] 2015-05-29 22:22
I'll keep this open until that's certain.

**Comment by sigmavirus24** [comment] 2015-05-29 23:01
Confirmed that this was in fact a tox 2.0 problem. Closing as invalid.

For other people who find this, the fix in OpenStack was to use tox's `setenv` config option to set `LC_ALL="en_US.UTF_8"`. The problem is fundamentally that the locale settings aren't being allowed through by tox. You should also be able to use `passenv` to allow those variables through instead of forcing a specific locale setting.

**Closed by sigmavirus24** 2015-05-29 23:01 UTC
